plugins {
    id 'java-library'
}

dependencies {
    implementation platform(libs.spring.boot.bom)

    implementation project(':note:contract')
    implementation project(':note:service')
    implementation project(':note:presentation:rest')
    implementation project(':note:persistence:jpa')
    implementation project(':note:messaging:outbox')
    implementation project(':note:messaging:kafka')

    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.data.jpa
}
