plugins {
    id 'java-library'
}

dependencies {
    api project(':note:contract')

    implementation platform(libs.spring.boot.bom)

    implementation project(':note:messaging:outbox')
    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.data.jpa

    testImplementation libs.spring.boot.starter.test
}
