spring.application.name=note-service-jdbc-mysql
spring.mvc.problemdetails.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/notedb
spring.datasource.username=notedb
spring.datasource.password=notedb
