spring.application.name=user-note-service-r2dbc-mysql
spring.webflux.problemdetails.enabled=true
spring.r2dbc.url=r2dbc:mysql://localhost:3306/usernotedb
spring.r2dbc.username=usernotedb
spring.r2dbc.password=usernotedb
