plugins {
    alias(libs.plugins.spring.boot)
    id 'java'
}

dependencies {
    implementation platform(libs.spring.boot.bom)

    implementation project(':crud:contract')
    implementation project(':note:runtime:spring')
    implementation project(':user:runtime:spring')
    implementation project(':auth:runtime:spring')
    implementation project(':user-note:runtime:spring')

    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.webmvc
    implementation libs.spring.boot.starter.data.jpa
    implementation libs.spring.boot.starter.actuator

    runtimeOnly libs.h2

    testImplementation libs.spring.boot.starter.test
    testImplementation project(':note:messaging:kafka')
    testImplementation project(':note:messaging:outbox')
}

tasks.named('bootJar') {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
