plugins {
    id 'java'
    id 'io.spring.javaformat'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

checkstyle {
    toolVersion = "9.3"
    configFile = rootProject.file('gradle/checkstyle/checkstyle.xml')
}

//applyDefaultConfig() added in 0.0.48 — not available on Maven Central; keep commented
//springJavaFormat {
//	checkstyle {
//		applyDefaultConfig()
//	}
//}
