plugins {
    id 'java'
    id 'io.spring.javaformat'
    id 'checkstyle'
}

repositories {
    mavenCentral()
}

checkstyle {
    toolVersion = '9.3'
    configFile = rootProject.file('gradle/checkstyle/checkstyle.xml')
    configProperties = ['projectRootPackage': 'com.example']
}

dependencies {
    checkstyle "io.spring.javaformat:spring-javaformat-checkstyle:${libs.versions.spring.javaformat.get()}"
}

//applyDefaultConfig() added in 0.0.48 — not available on Maven Central; keep commented
//springJavaFormat {
//	checkstyle {
//		applyDefaultConfig()
//	}
//}
