import org.gradle.api.plugins.BasePluginExtension
import org.gradle.api.plugins.JavaBasePlugin
import org.gradle.api.plugins.JavaPluginExtension
import org.gradle.api.tasks.testing.Test

subprojects {
    group = "com.example.${project.path.substring(1).replace(':', '.')}"
    version = '0.0.1-SNAPSHOT'

    plugins.withId('base') {
        extensions.configure(BasePluginExtension) { baseExtension ->
            baseExtension.archivesName = project.path.substring(1).replace(':', '-')
        }
    }

    plugins.withType(JavaBasePlugin).configureEach {
        extensions.configure(JavaPluginExtension) { javaExtension ->
            javaExtension.toolchain.languageVersion = JavaLanguageVersion.of(21)
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }
}
