subprojects {
    plugins.withId('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(
                    rootProject.file('.java-version').text.trim().toInteger()
                )
            }
        }
        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
        dependencies {
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        }
    }
}
