springBootVersion=4.0.6
dependencyManagementVersion=1.1.7
springJavaformatVersion=0.0.47
errorpronePluginVersion=5.1.0

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn