include ':gateway:application'
include ':config:application'
include ':registry:application'

include ':auth:application'

include ':user:application'
include ':user:webmvc'
include ':user:data-jpa'

include ':note:application'
include ':note:domain'
include ':note:webmvc'
include ':note:data-jpa'

include ':user-note:application'
include ':user-note:domain'
include ':user-note:webmvc'
include ':user-note:data-jpa'