pluginManagement {
    includeBuild("build-logic")
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "notes-spring"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":auth:application")

include(":config:application")

include(":gateway:application")

include(":registry:application")

include(":note:application-h2-jpa")
include(":note:application-mysql-jpa")
include(":note:application-postgresql-jpa")
include(":note:application-h2-jdbc")
include(":note:application-mysql-jdbc")
include(":note:application-postgresql-jdbc")
include(":note:application-mongodb")
include(":note:application-h2-r2dbc")
include(":note:application-mysql-r2dbc")
include(":note:application-postgresql-r2dbc")
include(":note:application-mongodb-reactive")
include(":note:domain")
include(":note:contract")
include(":note:contract-reactive")
include(":note:webmvc")
include(":note:webflux")
include(":note:data-jpa")
include(":note:data-mongodb")
include(":note:data-jdbc")
include(":note:data-r2dbc")
include(":note:data-mongodb-reactive")

project(":note:application-h2-jpa").projectDir = file("note/application/application-h2-jpa")
project(":note:application-mysql-jpa").projectDir = file("note/application/application-mysql-jpa")
project(":note:application-postgresql-jpa").projectDir = file("note/application/application-postgresql-jpa")
project(":note:application-h2-jdbc").projectDir = file("note/application/application-h2-jdbc")
project(":note:application-mysql-jdbc").projectDir = file("note/application/application-mysql-jdbc")
project(":note:application-postgresql-jdbc").projectDir = file("note/application/application-postgresql-jdbc")
project(":note:application-mongodb").projectDir = file("note/application/application-mongodb")
project(":note:application-h2-r2dbc").projectDir = file("note/application/application-h2-r2dbc")
project(":note:application-mysql-r2dbc").projectDir = file("note/application/application-mysql-r2dbc")
project(":note:application-postgresql-r2dbc").projectDir = file("note/application/application-postgresql-r2dbc")
project(":note:application-mongodb-reactive").projectDir = file("note/application/application-mongodb-reactive")
project(":note:domain").projectDir = file("note/domain/domain")
project(":note:contract").projectDir = file("note/domain/contract")
project(":note:contract-reactive").projectDir = file("note/domain/contract-reactive")
project(":note:webmvc").projectDir = file("note/presentation/webmvc")
project(":note:webflux").projectDir = file("note/presentation/webflux")
project(":note:data-jpa").projectDir = file("note/persistence/data-jpa")
project(":note:data-mongodb").projectDir = file("note/persistence/data-mongodb")
project(":note:data-jdbc").projectDir = file("note/persistence/data-jdbc")
project(":note:data-r2dbc").projectDir = file("note/persistence/data-r2dbc")
project(":note:data-mongodb-reactive").projectDir = file("note/persistence/data-mongodb-reactive")

include(":user:application-h2-jpa")
include(":user:application-mysql-jpa")
include(":user:application-postgresql-jpa")
include(":user:application-h2-jdbc")
include(":user:application-mysql-jdbc")
include(":user:application-postgresql-jdbc")
include(":user:application-mongodb")
include(":user:application-h2-r2dbc")
include(":user:application-mysql-r2dbc")
include(":user:application-postgresql-r2dbc")
include(":user:application-mongodb-reactive")
include(":user:domain")
include(":user:contract")
include(":user:contract-reactive")
include(":user:webmvc")
include(":user:webflux")
include(":user:data-jpa")
include(":user:data-mongodb")
include(":user:data-jdbc")
include(":user:data-r2dbc")
include(":user:data-mongodb-reactive")

project(":user:application-h2-jpa").projectDir = file("user/application/application-h2-jpa")
project(":user:application-mysql-jpa").projectDir = file("user/application/application-mysql-jpa")
project(":user:application-postgresql-jpa").projectDir = file("user/application/application-postgresql-jpa")
project(":user:application-h2-jdbc").projectDir = file("user/application/application-h2-jdbc")
project(":user:application-mysql-jdbc").projectDir = file("user/application/application-mysql-jdbc")
project(":user:application-postgresql-jdbc").projectDir = file("user/application/application-postgresql-jdbc")
project(":user:application-mongodb").projectDir = file("user/application/application-mongodb")
project(":user:application-h2-r2dbc").projectDir = file("user/application/application-h2-r2dbc")
project(":user:application-mysql-r2dbc").projectDir = file("user/application/application-mysql-r2dbc")
project(":user:application-postgresql-r2dbc").projectDir = file("user/application/application-postgresql-r2dbc")
project(":user:application-mongodb-reactive").projectDir = file("user/application/application-mongodb-reactive")
project(":user:domain").projectDir = file("user/domain/domain")
project(":user:contract").projectDir = file("user/domain/contract")
project(":user:contract-reactive").projectDir = file("user/domain/contract-reactive")
project(":user:webmvc").projectDir = file("user/presentation/webmvc")
project(":user:webflux").projectDir = file("user/presentation/webflux")
project(":user:data-jpa").projectDir = file("user/persistence/data-jpa")
project(":user:data-mongodb").projectDir = file("user/persistence/data-mongodb")
project(":user:data-jdbc").projectDir = file("user/persistence/data-jdbc")
project(":user:data-r2dbc").projectDir = file("user/persistence/data-r2dbc")
project(":user:data-mongodb-reactive").projectDir = file("user/persistence/data-mongodb-reactive")

include(":user-note:application-h2-jpa")
include(":user-note:application-mysql-jpa")
include(":user-note:application-postgresql-jpa")
include(":user-note:application-h2-jdbc")
include(":user-note:application-mysql-jdbc")
include(":user-note:application-postgresql-jdbc")
include(":user-note:application-mongodb")
include(":user-note:application-h2-r2dbc")
include(":user-note:application-mysql-r2dbc")
include(":user-note:application-postgresql-r2dbc")
include(":user-note:application-mongodb-reactive")
include(":user-note:domain")
include(":user-note:contract")
include(":user-note:contract-reactive")
include(":user-note:webmvc")
include(":user-note:webflux")
include(":user-note:data-jpa")
include(":user-note:data-mongodb")
include(":user-note:data-jdbc")
include(":user-note:data-r2dbc")
include(":user-note:data-mongodb-reactive")

project(":user-note:application-h2-jpa").projectDir = file("user-note/application/application-h2-jpa")
project(":user-note:application-mysql-jpa").projectDir = file("user-note/application/application-mysql-jpa")
project(":user-note:application-postgresql-jpa").projectDir = file("user-note/application/application-postgresql-jpa")
project(":user-note:application-h2-jdbc").projectDir = file("user-note/application/application-h2-jdbc")
project(":user-note:application-mysql-jdbc").projectDir = file("user-note/application/application-mysql-jdbc")
project(":user-note:application-postgresql-jdbc").projectDir = file("user-note/application/application-postgresql-jdbc")
project(":user-note:application-mongodb").projectDir = file("user-note/application/application-mongodb")
project(":user-note:application-h2-r2dbc").projectDir = file("user-note/application/application-h2-r2dbc")
project(":user-note:application-mysql-r2dbc").projectDir = file("user-note/application/application-mysql-r2dbc")
project(":user-note:application-postgresql-r2dbc").projectDir = file("user-note/application/application-postgresql-r2dbc")
project(":user-note:application-mongodb-reactive").projectDir = file("user-note/application/application-mongodb-reactive")
project(":user-note:domain").projectDir = file("user-note/domain/domain")
project(":user-note:contract").projectDir = file("user-note/domain/contract")
project(":user-note:contract-reactive").projectDir = file("user-note/domain/contract-reactive")
project(":user-note:webmvc").projectDir = file("user-note/presentation/webmvc")
project(":user-note:webflux").projectDir = file("user-note/presentation/webflux")
project(":user-note:data-jpa").projectDir = file("user-note/persistence/data-jpa")
project(":user-note:data-mongodb").projectDir = file("user-note/persistence/data-mongodb")
project(":user-note:data-jdbc").projectDir = file("user-note/persistence/data-jdbc")
project(":user-note:data-r2dbc").projectDir = file("user-note/persistence/data-r2dbc")
project(":user-note:data-mongodb-reactive").projectDir = file("user-note/persistence/data-mongodb-reactive")
