pluginManagement {
    includeBuild("build-logic")
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "notes-spring"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":auth:application")

include(":config:application")

include(":gateway:application")

include(":registry:application")

include(":note:application-h2-jpa")
include(":note:application-mysql-jpa")
include(":note:application-postgresql-jpa")
include(":note:application-h2-jdbc")
include(":note:application-mysql-jdbc")
include(":note:application-postgresql-jdbc")
include(":note:application-mongodb")
include(":note:application-h2-r2dbc")
include(":note:application-mysql-r2dbc")
include(":note:application-postgresql-r2dbc")
include(":note:application-mongodb-reactive")
include(":note:domain")
include(":note:contract")
include(":note:contract-reactive")
include(":note:webmvc")
include(":note:webflux")
include(":note:data-jpa")
include(":note:data-mongodb")
include(":note:data-jdbc")
include(":note:data-r2dbc")
include(":note:data-mongodb-reactive")

include(":user:application-h2-jpa")
include(":user:application-mysql-jpa")
include(":user:application-postgresql-jpa")
include(":user:application-h2-jdbc")
include(":user:application-mysql-jdbc")
include(":user:application-postgresql-jdbc")
include(":user:application-mongodb")
include(":user:application-h2-r2dbc")
include(":user:application-mysql-r2dbc")
include(":user:application-postgresql-r2dbc")
include(":user:application-mongodb-reactive")
include(":user:domain")
include(":user:contract")
include(":user:contract-reactive")
include(":user:webmvc")
include(":user:webflux")
include(":user:data-jpa")
include(":user:data-mongodb")
include(":user:data-jdbc")
include(":user:data-r2dbc")
include(":user:data-mongodb-reactive")

include(":user-note:application-h2-jpa")
include(":user-note:application-mysql-jpa")
include(":user-note:application-postgresql-jpa")
include(":user-note:application-h2-jdbc")
include(":user-note:application-mysql-jdbc")
include(":user-note:application-postgresql-jdbc")
include(":user-note:application-mongodb")
include(":user-note:application-h2-r2dbc")
include(":user-note:application-mysql-r2dbc")
include(":user-note:application-postgresql-r2dbc")
include(":user-note:application-mongodb-reactive")
include(":user-note:domain")
include(":user-note:contract")
include(":user-note:contract-reactive")
include(":user-note:webmvc")
include(":user-note:webflux")
include(":user-note:data-jpa")
include(":user-note:data-mongodb")
include(":user-note:data-jdbc")
include(":user-note:data-r2dbc")
include(":user-note:data-mongodb-reactive")
