spring.application.name=user-note-service-mysql-jdbc
spring.mvc.problemdetails.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/usernotedb
spring.datasource.username=usernotedb
spring.datasource.password=usernotedb
