services:
  mysql:
    image: 'mysql:9'
    environment:
      - 'MYSQL_DATABASE=notedb'
      - 'MYSQL_USER=notedb'
      - 'MYSQL_PASSWORD=notedb'
      - 'MYSQL_ROOT_PASSWORD=notedb'
    ports:
      - '3306'
