plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    implementation "io.spring.gradle:dependency-management-plugin:${dependencyManagementVersion}"
}
