spring.application.name=notes-spring
spring.mvc.problemdetails.enabled=true
app.notes.base-url=/notes
app.notes.messages.hello-world=Hello, World
app.notes.messages.note-not-found=Note with id %s not found
app.notes.messages.cannot-update=Cannot update. Note with id %s not found
app.notes.messages.cannot-delete=Cannot delete. Note with id %s not found