spring.application.name=notes-spring
spring.mvc.problemdetails.enabled=true

app.notes.base-url=/api/notes

app.notes.messages.note.create.success=app.notes.note.create.success
app.notes.messages.note.create.failure=app.notes.note.create.failure

app.notes.messages.note.read.success=app.notes.note.read.success
app.notes.messages.note.read.failure.general=app.notes.note.read.failure.general
app.notes.messages.note.read.failure.not-found=app.notes.note.read.failure.not-found

app.notes.messages.note.update.success=app.notes.note.update.success
app.notes.messages.note.update.failure.general=app.notes.note.update.failure.general
app.notes.messages.note.update.failure.not-found=app.notes.note.update.failure.not-found

app.notes.messages.note.delete.success=app.notes.note.delete.success
app.notes.messages.note.delete.failure.general=app.notes.note.delete.failure.general
app.notes.messages.note.delete.failure.not-found=app.notes.note.delete.failure.not-found
