import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
	id 'java'
	id 'io.spring.dependency-management'
	id 'com.example.java-codequality'
}

dependencyManagement {
	imports {
		mavenBom(SpringBootPlugin.BOM_COORDINATES)
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-h2console'
	runtimeOnly 'com.h2database:h2'
}
