plugins {
	id 'com.example.java-codequality-javaformat'
	id 'com.example.java-codequality-errorprone'
	id 'com.example.java-codequality-jacoco'
	id 'com.example.java-codequality-jacoco-report-aggregation'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(rootProject.file('.java-version').text.trim().toInteger())
	}
}
