import net.ltgt.gradle.errorprone.CheckSeverity

plugins {
	id 'java'
	id 'net.ltgt.errorprone'
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly 'org.jspecify:jspecify:1.0.0'
	errorprone 'com.google.errorprone:error_prone_core:2.50.0'
	errorprone 'com.uber.nullaway:nullaway:0.13.7'
}

tasks.withType(JavaCompile).configureEach {
	options.errorprone {
		check('NullAway', CheckSeverity.ERROR)
		option('NullAway:AnnotatedPackages', 'com.example')
	}
	if (name.toLowerCase().contains('test')) {
		options.errorprone {
			disable('NullAway')
		}
	}
}
