spring.application.name=note-service-r2dbc-mysql
spring.webflux.problemdetails.enabled=true
spring.r2dbc.url=r2dbc:mysql://localhost:3306/notedb
spring.r2dbc.username=notedb
spring.r2dbc.password=notedb
