[versions]
checkstyle = "13.10.0"
errorprone-core = "2.50.0"
errorprone-plugin = "5.1.0"
jacoco = "0.8.15"
jakarta-validation = "3.1.1"
jspecify = "1.0.1"
junit-jupiter = "6.1.3"
junit-platform = "6.1.3"
nullaway = "0.13.8"
pmd = "7.24.0"
reactor-core = "3.8.6"
spotbugs-plugin = "6.5.11"
spotless-plugin = "8.9.0"
spring-boot-plugin = "4.1.0"
spring-cloud = "2025.1.2"
spring-dependency-management-plugin = "1.1.7"
