[versions]
spring-boot = "4.0.6"
reactor-core = "3.8.5"
spring-cloud = "2025.1.2"
spring-dependency-management = "1.1.7"
spring-javaformat = "0.0.47"
errorprone-plugin = "5.1.0"
errorprone-core = "2.50.0"
nullaway = "0.13.7"
jspecify = "1.0.0"
jacoco = "0.8.14"
checkstyle = "9.3"
junit-jupiter = "6.0.3"
junit-platform = "6.0.3"
