plugins {
    id 'spring-boot-application-conventions'
    id 'spring-h2-database-conventions'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
    implementation project(':domain')
    implementation project(':data-jpa')
    implementation project(':webmvc')
}
