plugins {
    id 'java-library'
}

dependencies {
    implementation platform(libs.spring.boot.bom)

    implementation project(':crud:contract')
    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.webmvc
    implementation libs.spring.boot.starter.validation

    testImplementation libs.spring.boot.starter.test
}
