plugins {
    id 'com.example.spring-boot-application'
    id 'com.example.spring-boot-h2-database'
}

dependencies {
    implementation project(':note:domain')
    implementation project(':note:webmvc')
    implementation project(':note:data-jpa')
    implementation project(':note:data-contract')
}
