plugins {
    id 'com.example.spring-boot-application'
    id 'com.example.spring-boot-h2-database'
}

dependencies {
    implementation project(':user-note:domain')
    implementation project(':user-note:data-contract')
    implementation project(':user-note:webmvc')
    implementation project(':user-note:data-jpa')
}
