plugins {
    id 'spring-boot-application-conventions'
    id 'spring-boot-h2-database-conventions'
}

dependencies {
    implementation project(':user-note:domain')
    implementation project(':user-note:service')
    implementation project(':user-note:webmvc')
    implementation project(':user-note:data-jpa')
}
