spring.application.name=user-note-service-jpa-postgresql
spring.mvc.problemdetails.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/usernotedb
spring.datasource.username=usernotedb
spring.datasource.password=usernotedb
