plugins {
    id 'java-library'
}

dependencies {
    implementation platform(libs.spring.boot.bom)

    implementation project(':user:contract')
    implementation project(':crud:presentation:rest')

    implementation libs.spring.boot.starter.webmvc
    implementation libs.spring.boot.starter.validation

    testImplementation libs.spring.boot.starter.test
}
