plugins {
    id 'java-library'
}

dependencies {
    implementation platform(libs.spring.boot.bom)

    implementation project(':auth:contract')
    implementation project(':auth:service')
    implementation project(':auth:presentation:rest')
    implementation project(':auth:persistence:jpa')
    implementation project(':user:contract')

    implementation libs.spring.boot.starter
    implementation libs.spring.boot.starter.data.jpa
}
