spring.application.name=user-note-service-postgresql-r2dbc
spring.webflux.problemdetails.enabled=true
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/usernotedb
spring.r2dbc.username=usernotedb
spring.r2dbc.password=usernotedb
