services:
  mysql:
    image: 'mysql:9'
    environment:
      - 'MYSQL_DATABASE=usernotedb'
      - 'MYSQL_USER=usernotedb'
      - 'MYSQL_PASSWORD=usernotedb'
      - 'MYSQL_ROOT_PASSWORD=usernotedb'
    ports:
      - '3306'
