spring.application.name=user-service-jdbc-postgresql
spring.mvc.problemdetails.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=userdb
spring.datasource.password=userdb
