spring.application.name=user-service-r2dbc-mysql
spring.webflux.problemdetails.enabled=true
spring.r2dbc.url=r2dbc:mysql://localhost:3306/userdb
spring.r2dbc.username=userdb
spring.r2dbc.password=userdb
